title: Rise of the robots
author: Michelle Sandford
email: michelle-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a project created for the #100DaysOfCode Challenge

# social links
twitter_username: @msandfor
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
